### ISSUE TITLE
StreamEntries shared Data

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#17]
for streaming there are two classes `ZIKStreamEntry` & `ZIKLogStreamEntry` that the `ZIKStreamListener` listener can return, however at the moment it is returned as an object  `void onUpdate(Object object);` 

They both share a common object in `String topic`

Can it be returned as a joint interface or a superclass?

like 

`public class ZIKLogStreamEntry extends ZIKStreamEntry {`

`public class ZIKObjectStreamEntry extends ZIKStreamEntry {`

```
abstract class ZIKStreamEntry {
   @NonNull private final String topic;

...

    @NonNull
    public String getName() {
        return topic.substring(0, topic.indexOf("/"));
    }

    @NonNull
    public UUID getUUID() {
        int positionFirstBreak = topic.indexOf("/");
        int positionSecondBreak = topic.indexOf("/", positionFirstBreak + 1);
        return UUID.fromString(topic.substring(positionFirstBreak + 1, positionSecondBreak - 1));
    }

    @NonNull
    public String getTitle() {
        int positionThirdBreak = topic.lastIndexOf("/");
        return topic.substring(positionThirdBreak + 1, topic.length());
    }
}
```

then the listener becomes `onUpdate(ZIKStreamEntry entry);`

Something like this?

**Comment by RobertWalsh** [comment]
I was working on a concept like this but it ended up feeling really clunky.  

There are actually three classes  `ZIKStreamEntry`, `ZIKLogStreamEntry` and `ZIKDevice` that the `ZIKStreamListener` listener can return.  

So this means we couldn't have `onUpdate(ZIKStreamEntry entry);`.  We would probably need to use generics and that's where things gets a little messy.  

While have a abstract class idea for `ZIKStreamEntry` is probably the right way to go, I don't think it is super necessary right now as it will cause a bunch of changes with the JSON parsing and I don't see a huge upside.

For the record I don't really like the implementation `onUpdate(Object object);`.  At the moment I think I will close this but probably will need to come back to it at some point.
