### ISSUE TITLE
No tests around ZikDevice.transition

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#20]
Nice to see some tests for the `transition` methods to ensure they don't break and to see how they work

https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/main/java/com/apigee/zettakit/ZIKDevice.java#L94-L137

**Comment by RobertWalsh** [comment]
Added some tests here: https://github.com/zettaapi/zetta-sdk-android/commit/53a714f7618a71ceac093a16f5ded541ef74eed8
