### ISSUE TITLE
ZikDevice name & state nullability

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#21]
can ZikDevice.name and ZikDevice.state be changed from `@Nullable` to `@NonNull` ? It should be an illegale state if a device doesn't have a name, i.e. it's a contract with the api that a device always has a name and state. If state is not there I think a blank string `""` would make more sense

https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/main/java/com/apigee/zettakit/ZIKDevice.java#L68-L79

**Comment by RobertWalsh** [comment]
See commit: https://github.com/zettaapi/zetta-sdk-android/commit/8de03aa44730f9ee6e947e8fb33d011c163c5a40

I decided to have both just end up being a blank string ```""```.  I think it makes sense even if the name isn't there to still have it be a valid device at the moment until I get more solid confirmation this does indeed break its contract with the API's.
