### ISSUE TITLE
Client callbacks improvement

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#4]
All callbacks should have a `success` and a `failure` callback

for example: https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/main/java/com/apigee/zettakit/callbacks/ZIKServersCallback.java#L10

```
public interface ZIKServersCallback {
    void onFinished(@Nullable final List<ZIKServer> servers);
}
```

would be easier for client use as:

```
public interface ZikServersCallback {
    void onSuccess(@NonNull List<ZIKServer> servers);
    void onFailure(@NonNull ZikException e);
}
```

**Comment by RobertWalsh** [comment]
All callback classes now have `onSuccess` and a `onFailure` callbacks.

For now the `onFailure` callback method has an `IOException` as the exception parameter.  This may change in the future but for now that is what it is.
