### ISSUE TITLE
Variables passed to client should not be null if it can be avoided

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#6]
https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/main/java/com/apigee/zettakit/callbacks/ZIKServersCallback.java#L10

`public void onFinished(@Nullable List<ZIKServer> servers) {`

with things like collections, its much better for the client to receive an empty collection than a null item.

This method signature would be better as:

`public void onFinished(@NonNull List<ZIKServer> servers) {`

and when you want to call it:

```
if(servers == null) {
   servers = Collections.emptyList();
}
callback.onFinished(servers);
```

This applies for all maps, lists that are in the public api.

**Comment by RobertWalsh** [comment]
Callbacks return non null lists now. I believe I converted all maps and lists from the public api to return empty lists instead of null as well.  If you see any others please let me know.
