### ISSUE TITLE
Getting one devices details

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#8]
If i want to show a screen with one device details, it would be good if there was an api call just for that one devices details. Passing a `DeviceId` to get the details.

At the moment you have to get the server details, then all devices on that servers details and then that select the one you want.

**Comment by RobertWalsh** [comment]
Instead of using just the `ZIKDeviceId` to load one device it makes more sense to actually fetch from the `ZIKDevice` class itself which is the same way the iOS SDK implements this.

Hence I added `ZIKDevice.fetch()` methods so you can fetch the one device on its own.

    ...
    @Override
    public void onSuccess(@NonNull List<ZIKDevice> devices) {
        ZIKDevice device = devices.get(0);
        device.fetchAsync(new ZIKDeviceCallback() {
            @Override
            public void onSuccess(@NonNull ZIKDevice device) {
                // This device has all the information loaded.
            }
            @Override
            public void onFailure(@NonNull IOException exception) { }
        });
    }
    ...
